// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
// import 'src/core/stores/store-flag';
import 'quasar/dist/types/feature-flag';

declare module 'quasar/dist/types/feature-flag' {
    interface QuasarFeatureFlags {
        store: true;
    }
}
